"use client";
import { useState } from "react";
import { LogOut, Plus, UploadCloud } from "lucide-react";
import type { Project } from "@/lib/projects";

export function AdminPanel({ initialProjects }: { initialProjects: Project[] }) {
  const [projects, setProjects] = useState(initialProjects); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setMessage(""); const form = new FormData(e.currentTarget); const res = await fetch("/api/projects", { method: "POST", body: form }); const data = await res.json(); setLoading(false); if (!res.ok) return setMessage(data.error || "Não foi possível salvar."); setProjects([data.project, ...projects]); e.currentTarget.reset(); setMessage("Projeto publicado com sucesso."); }
  return <div className="adminShell"><aside><a className="brand" href="/"><span className="brandMark">V</span><span>VBG<small>AGENCY</small></span></a><nav><a className="active">Projetos</a><a href="/">Ver site</a></nav><form action="/api/admin/logout" method="post"><button><LogOut size={17}/> Sair</button></form></aside><section><header><div><span>PAINEL ADMINISTRATIVO</span><h1>Projetos</h1></div><b>{projects.length} publicados</b></header><form className="projectForm" onSubmit={submit}><div className="formTitle"><Plus/><div><h2>Novo projeto</h2><p>Preencha as informações para publicar no site.</p></div></div><label>Título<input name="title" required placeholder="Nome do projeto"/></label><label>Descrição<textarea name="description" required placeholder="Conte o desafio e a solução" rows={4}/></label><label>Tecnologias<input name="technologies" required placeholder="Next.js, TypeScript, MySQL"/><small>Separe por vírgulas</small></label><label className="upload"><UploadCloud/><b>Adicionar imagem</b><span>PNG, JPG ou WEBP · máximo 5 MB</span><input name="image" required type="file" accept="image/png,image/jpeg,image/webp"/></label><button className="publish" disabled={loading}>{loading ? "Publicando..." : "Publicar projeto"}</button>{message && <p className="message">{message}</p>}</form><div className="adminList">{projects.map(p => <article key={p.id}><img src={p.imageUrl} alt=""/><div><h3>{p.title}</h3><p>{p.technologies.join(" · ")}</p></div></article>)}</div></section></div>;
}
